openapi: 3.0.3
info:
  title: RIMAC Appointments API
  version: 1.0.0
paths:
  /appointments:
    post:
      summary: Crear solicitud de cita (asíncrono)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [insuredId, scheduleId, countryISO]
              properties:
                insuredId: { type: string, pattern: "^\\d{5}$" }
                scheduleId: { type: integer }
                countryISO: { type: string, enum: [PE, CL] }
      responses:
        "202": { description: Aceptado }
  /appointments/{insuredId}:
    get:
      summary: Listar citas por asegurado
      parameters:
        - in: path
          name: insuredId
          required: true
          schema: { type: string, pattern: "^\\d{5}$" }
      responses:
        "200": { description: OK }
